<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Aetheric.Provisioning.Application/Aetheric.Provisioning.Application.csproj" />
    <ProjectReference Include="../../Providers/AethericForge.Runtime.Providers.Identity.Keycloak/AethericForge.Runtime.Providers.Identity.Keycloak.csproj" />
    <InternalsVisibleTo Include="Aetheric.Provisioning.Tests" />
  </ItemGroup>
</Project>
