<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>AethericForge.Runtime.Providers.Archive.S3</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AWSSDK.S3" Version="4.0.100.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Abstractions\Interfaces\AethericForge.Runtime.Abstractions.Interfaces\AethericForge.Runtime.Abstractions.Interfaces.csproj" />
      <ProjectReference Include="..\..\Models\AethericForge.Runtime.Models\AethericForge.Runtime.Models.csproj" />
    </ItemGroup>

</Project>
